eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: atlas-instance-${random.uuid}
server:
  port: 8080
spring:
  application:
    name: atlas
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/atlas-bot?useSSL=false&serverTimezone=UTC
    username: borz0y
    password: 58rjK[jP1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true