version: '3'

services:
  eureka:
    build: ./eureka
    restart: always
    ports:
      - 8761:8761
    environment:
      - EUREKA_HOST=http://eureka:8761/eureka/
  cryptohouse:
    build: ./crypto-house
    restart: always
    ports:
      - 9090:9090
    environment:
      - EUREKA_HOST=http://eureka:8761/eureka/
  atlas:
    build: ./atlas
    ports:
      - 8082:8080
    restart: always
    environment:
      - EUREKA_HOST=http://eureka:8761/eureka/
