package ru.thirteenth.atlas.model;

public enum State {
    START,INFO_PAGE,MAIN_MENU, MARKET_CONDITION_MAIN, CHECK_MARKET_CONDITION,
    FEAR_AND_GREED,CRYPTOCURRENCY_MENU, COIN_INFO_MENU, OPTION_MENU, OPTION_LANGUAGE_MENU,
    MARKET_MENU,TOP_15_CAP,COIN_INFO_NAME_PATTERN,COIN_INFO_SUFFIX_PATTERN, CONVERTATOR_MENU,
    CRYPT_TO_FIAT_CONVERTATOR_MENU, CRYPTO_TO_FIAT_SELECT_RUB, CRYPTO_TO_FIAT_SELECT_USD,
    FIAT_TO_CRYPTO_SELECT_USD, FIAT_TO_CRYPTO_SELECT_RUB
}
