package ru.thirteenth.atlas.entity;

public enum State {
    START,INFO_PAGE,MAIN_MENU, MARKET_CONDITION_MAIN, CHECK_MARKET_CONDITION,
    FEAR_AND_GREED,CRYPTOCURRENCY_MENU, COIN_INFO_MENU, OPTION_MENU, OPTION_LANGUAGE_MENU,
    MARKET_MENU,TOP_15_CAP
}
